;===============================================================================
; AUTO-GENERATED CODE: Render all 24 tile rows
; Generated by: gen_render_rows.py
;===============================================================================
; This code renders a full screen of tiles (32 columns × 24 rows)
; Input: C = column number (0-31)
; Expects: camera_x, tile_map, charset to be defined
; Clobbers: A, BC, DE, HL
; Stack: Pushes BC on entry, pops BC on exit (balanced)
;===============================================================================

    ;===========================================================================
    ; ROW 0 (Character row 0, scanlines 0-7)
    ;===========================================================================
    push bc             ; save column counter for all rows
    ld d, $40
    ld e, c
    ld h, (tile_map / 256) + 0
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 1 (Character row 1, scanlines 8-15)
    ;===========================================================================
    pop bc
    push bc
    ld d, $40
    ld a, c
    add a, 32
    ld e, a
    ld h, (tile_map / 256) + 1
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 2 (Character row 2, scanlines 16-23)
    ;===========================================================================
    pop bc
    push bc
    ld d, $40
    ld a, c
    add a, 64
    ld e, a
    ld h, (tile_map / 256) + 2
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 3 (Character row 3, scanlines 24-31)
    ;===========================================================================
    pop bc
    push bc
    ld d, $40
    ld a, c
    add a, 96
    ld e, a
    ld h, (tile_map / 256) + 3
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 4 (Character row 4, scanlines 32-39)
    ;===========================================================================
    pop bc
    push bc
    ld d, $40
    ld a, c
    add a, 128
    ld e, a
    ld h, (tile_map / 256) + 4
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 5 (Character row 5, scanlines 40-47)
    ;===========================================================================
    pop bc
    push bc
    ld d, $40
    ld a, c
    add a, 160
    ld e, a
    ld h, (tile_map / 256) + 5
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 6 (Character row 6, scanlines 48-55)
    ;===========================================================================
    pop bc
    push bc
    ld d, $40
    ld a, c
    add a, 192
    ld e, a
    ld h, (tile_map / 256) + 6
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 7 (Character row 7, scanlines 56-63)
    ;===========================================================================
    pop bc
    push bc
    ld d, $40
    ld a, c
    add a, 224
    ld e, a
    ld h, (tile_map / 256) + 7
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 8 (Character row 8, scanlines 64-71)
    ; MIDDLE THIRD
    ;===========================================================================
    pop bc
    push bc
    ld d, $48
    ld e, c
    ld h, (tile_map / 256) + 8
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 9 (Character row 9, scanlines 72-79)
    ;===========================================================================
    pop bc
    push bc
    ld d, $48
    ld a, c
    add a, 32
    ld e, a
    ld h, (tile_map / 256) + 9
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 10 (Character row 10, scanlines 80-87)
    ;===========================================================================
    pop bc
    push bc
    ld d, $48
    ld a, c
    add a, 64
    ld e, a
    ld h, (tile_map / 256) + 10
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 11 (Character row 11, scanlines 88-95)
    ;===========================================================================
    pop bc
    push bc
    ld d, $48
    ld a, c
    add a, 96
    ld e, a
    ld h, (tile_map / 256) + 11
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 12 (Character row 12, scanlines 96-103)
    ;===========================================================================
    pop bc
    push bc
    ld d, $48
    ld a, c
    add a, 128
    ld e, a
    ld h, (tile_map / 256) + 12
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 13 (Character row 13, scanlines 104-111)
    ;===========================================================================
    pop bc
    push bc
    ld d, $48
    ld a, c
    add a, 160
    ld e, a
    ld h, (tile_map / 256) + 13
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 14 (Character row 14, scanlines 112-119)
    ;===========================================================================
    pop bc
    push bc
    ld d, $48
    ld a, c
    add a, 192
    ld e, a
    ld h, (tile_map / 256) + 14
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 15 (Character row 15, scanlines 120-127)
    ;===========================================================================
    pop bc
    push bc
    ld d, $48
    ld a, c
    add a, 224
    ld e, a
    ld h, (tile_map / 256) + 15
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 16 (Character row 16, scanlines 128-135)
    ; BOTTOM THIRD
    ;===========================================================================
    pop bc
    push bc
    ld d, $50
    ld e, c
    ld h, (tile_map / 256) + 16
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 17 (Character row 17, scanlines 136-143)
    ;===========================================================================
    pop bc
    push bc
    ld d, $50
    ld a, c
    add a, 32
    ld e, a
    ld h, (tile_map / 256) + 17
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 18 (Character row 18, scanlines 144-151)
    ;===========================================================================
    pop bc
    push bc
    ld d, $50
    ld a, c
    add a, 64
    ld e, a
    ld h, (tile_map / 256) + 18
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 19 (Character row 19, scanlines 152-159)
    ;===========================================================================
    pop bc
    push bc
    ld d, $50
    ld a, c
    add a, 96
    ld e, a
    ld h, (tile_map / 256) + 19
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 20 (Character row 20, scanlines 160-167)
    ;===========================================================================
    pop bc
    push bc
    ld d, $50
    ld a, c
    add a, 128
    ld e, a
    ld h, (tile_map / 256) + 20
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 21 (Character row 21, scanlines 168-175)
    ;===========================================================================
    pop bc
    push bc
    ld d, $50
    ld a, c
    add a, 160
    ld e, a
    ld h, (tile_map / 256) + 21
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 22 (Character row 22, scanlines 176-183)
    ;===========================================================================
    pop bc
    push bc
    ld d, $50
    ld a, c
    add a, 192
    ld e, a
    ld h, (tile_map / 256) + 22
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; ROW 23 (Character row 23, scanlines 184-191)
    ;===========================================================================
    pop bc
    push bc
    ld d, $50
    ld a, c
    add a, 224
    ld e, a
    ld h, (tile_map / 256) + 23
    ld a, (camera_x)
    add a, c
    ld l, a
    ld a, (hl)
    ld l, a
    ld h, 0
    add hl, hl           ; * 2
    add hl, hl           ; * 4
    add hl, hl           ; * 8
    ld bc, charset
    add hl, bc
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl
    inc d
    ld a, (hl)
    ld (de), a
    inc hl

    ;===========================================================================
    ; Restore column counter and return
    ;===========================================================================
    pop bc              ; restore column counter

